#!/usr/bin/python

import sys
import os
import time
import getopt
import locale

import lastfm
import lastfm.client
import lastfm.marshaller

USAGE = """\
usage: lastfmsubmitd [--encoding ENC] [--artist ARTIST] [--title TITLE]
    [--length LEN] [--time STAMP] [--album ALBUM] [--mbid TRACKID]
    [--encoding ENC] [--stdout] [--debug] [--quiet] [--help]"""

if __name__ == '__main__':
    shortopts = 'e:a:s:l:d:b:m:sdqh'
    longopts = [
        'encoding=',
        'artist=',
        'title=',
        'length=',
        'time=',
        'album=',
        'mbid=',
        'stdout',
        'debug',
        'quiet',
        'help',
        ]

    try:
        opts, args = getopt.getopt(sys.argv[1:], shortopts, longopts)
    except getopt.GetoptError as e:
        print('lastfmsubmit: {}'.format(e), file=sys.stderr)
        print(USAGE, file=sys.stderr)
        sys.exit(1)

    sub = {}
    encoding = locale.getpreferredencoding()
    stdout = False
    debug = False
    stderr = True

    for opt, arg in opts:
        if opt in ('--encoding', '-e'):
            encoding = arg
        if opt in ('--debug', '-d'):
            debug = True
        if opt in ('--quiet', '-q'):
            stderr = False

    cli = lastfm.client.Client('lastfmsubmit')
    cli.open_log(debug, stderr)

    try:
        for opt, arg in opts:
            try:
                if opt in ('--artist', '-a'):
                    sub['artist'] = lastfm.marshaller.guess_enc(arg, encoding)
                elif opt in ('--title', '-t'):
                    sub['title'] = lastfm.marshaller.guess_enc(arg, encoding)
                elif opt in ('--length', '-l'):
                    sub['length'] = lastfm.marshaller.parse_length(arg)
                elif opt in ('--time', '-i'):
                    sub['time'] = time.strptime(arg, lastfm.TIME_FMT)
                elif opt in ('--album', '-b'):
                    sub['album'] = lastfm.marshaller.guess_enc(arg, encoding)
                elif opt in ('--mbid', '-m'):
                    sub['mbid'] = arg
                elif opt in ('--stdout', '-s'):
                    stdout = True
                elif opt in ('--help', '-h'):
                    print(USAGE)
                    sys.exit(0)
            except ValueError:
                print("lastfmsubmit: can't parse {}".format(opt), file=sys.stderr)
                sys.exit(1)

        if len(sub) == 0:
            print('lastfmsubmit: nothing specified', file=sys.stderr)
            print(USAGE, file=sys.stderr)
            sys.exit(1)
        if 'time' not in sub:
            sub['time'] = time.gmtime()

        if stdout:
            print(lastfm.marshaller.dump(sub))
        else:
            try:
                cli.log.debug('Sending {} to daemon'.format(lastfm.repr(sub)))
                cli.submit(sub)
            except IOError:
                cli.log.error("Can't write sub: {}".format(e))
                sys.exit(1)

    except SystemExit as e:
        sys.exit(e.args[0])
    except:
        import traceback
        einfo = traceback.format_exception(*sys.exc_info())
        cli.log.error('Aborting: {}'.format(''.join(einfo)))
        sys.exit(1)
